### ISSUE TITLE
Push latest changes to VS Code marketplace

### ISSUE THREAD

**Issue by rmorabia** [Mufanza/vs-code-e-ink-theme#2]
Hey mate, I updated my changes manually for months of using this theme to make the side paneling more light-themed. I checked this repo to see that you have made these changes to the side paneling to make it actually a true light-theme. However, these latest commits aren't in the version that has been pushed up to the VS Code Marketplace. Can you do that? Thank you!

**Comment by Mufanza** [comment]
Hi Radhika, thanks for reaching out!
The answer is yes and no :) I've been locked-out of my Microsoft publisher
account and can no longer update the old theme. Maybe it's possible to
retrieve the account somehow, but I lost patience after a few hours of
trying.
To solve the issue in an ugly, quickfix manner: I've simply created a new
publisher for the VS marketplace.
Here's a link to the new, up-to-date version of the theme:

https://marketplace.visualstudio.com/items?itemName=Mufanzaa.e-ink-theme-2

Cheers!
Peter

**Comment by rmorabia** [comment]
That works as well. Thanks for taking the time!
